image: node:lts-buster  # 使用稳定的 LTS Node.js 版本

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:  # 任务名必须为 pages
  stage: deploy
  script:
    # 1. 安装全局 Hexo CLI
    - npm install -g hexo-cli
    
    # 2. 安装项目依赖 (包含 webstack 主题)
    - npm install
    
    # 3. 生成静态文件 (自动创建 public 目录)
    - hexo generate
    
  artifacts:
    paths:
      - public  # 重要：必须指向 Hexo 生成的目录
  publish: public  

  # 仅在主分支部署 (根据需要修改分支名)
  only:
    - main  # 或 master/your-branch-name