image: node:lts-buster

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    # Hexo安装和构建
    - npm install -g hexo-cli
    - npm install
    - hexo clean
    - hexo generate  # 生成public目录
    - ls -l public
    
    # 可选：Webstack主题额外构建
    # - cd themes/webstack && npm install && npm run build
    # - cd ../..  # 返回项目根目录
  
  # 声明制品目录（必须包含网站文件）
  artifacts:
    paths:
      - public  # Hexo默认输出目录
  
  # 关键：必须声明发布目录
  publish: public 
  
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # 仅主分支部署
      when: on_success