image: node:20

pages:
  before_script:
    - npm install -g hexo-cli
    - npm install
  script:
    - hexo clean
    - hexo generate
  publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH